<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' '. $this->translate('Tocat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
<script type="text/javascript">

    $(function () {
      var $win = $(window);
      $win.resize(function () {
          if ($win.width() > 768)
              $(".navbar-nav > .dropdown > a").attr("data-toggle", "");
          else
              $(".navbar-nav > .dropdown > a").attr("data-toggle", "dropdown");
      }).resize();
      $(".dropdown-menu").find("input, button").each(function () {
          $(this).click(function (e) {
              e.stopPropagation();
          });
      });
    });
</script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Tocat') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->
        navigation('navigation')
        ->menu()
        ->setUlClass('nav navbar-nav')
        ->setPartial('layout/partial/top-menu/navigation.phtml');
    ?>

                    <ul class="nav navbar-nav pull-right">
                        <li class="right"> <span style="color: #f5f5f5;"><strong>Hello, <?=($this->zfcUserDisplayName())?'<a href="/user">'.$this->zfcUserDisplayName().'</a>':'guest'?></strong></span></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>