<?php  $this->headScript()
            ->prependFile($this->basePath() . '/tocat-user/js/controllers/admin-role.js')
            ->prependFile($this->basePath() . '/vendor/angular-ui-tree/dist/angular-ui-tree.min.js')
            ->prependFile($this->basePath() . '/vendor/angular/angular.min.js');
       $this->headLink()->prependStylesheet($this->basePath() . '/tocat-user/css/style.css');
?>

<script type="text/javascript">
    var URL_SAVE_ROLE_LIST = '<?php echo $this->url('zfcadmin/roles',array('action' => 'save-tree')) ?>';
    var URL_SHOW_ROLE_LIST = '<?php echo $this->url('zfcadmin/roles',array('action' => 'list')) ?>';
</script>

<!-- Nested node template -->
<script type="text/ng-template" id="nodes_renderer2.html">
  <div class="tree-node">
    <div class="pull-left tree-handle" ui-tree-handle>
      <span class="glyphicon glyphicon-list"></span>
    </div>
    <div class="tree-node-content">
        <div class="group-title angular-ui-tree-handle" ng-show="!node.editing">
            <a class="btn btn-success btn-xs" data-nodrag ng-click="moveNode(this)"><span class="glyphicon" ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed}"></span></a>
            {{node.roleId}}
            <a class="pull-right btn btn-danger btn-xs" data-nodrag ng-click="deleteNode(this)"><span class="glyphicon glyphicon-remove"></span></a>
            <a class="pull-right btn btn-primary btn-xs" data-nodrag ng-click="newSubItem(this)" style="margin-right: 8px;"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="" class="btn btn-primary btn-xs pull-right" data-nodrag="" ng-click="editItem(node)"  style="margin-right: 8px;"><span class="glyphicon glyphicon-pencil"></span></a>
        </div>
        <div class="group-title angular-ui-tree-handle ng-hide" data-nodrag="" ng-show="node.editing">
          <form class="form-inline ng-valid ng-dirty" role="form">
            <div class="form-group">
              <label class="sr-only" for="roleId">Role ID</label>
              <input class="form-control ng-valid ng-dirty" placeholder="Role ID" ng-model="node.roleId" type="text">
            </div>
            <button type="submit" class="btn btn-default" ng-click="saveItem(node)">Save</button>
            <button type="submit" class="btn btn-default" ng-click="cancelEditingItem(node)">Cancel</button>
          </form>
        </div>
    </div>
  </div>
  <ol ui-tree-nodes="" ng-model="node.nodes" ng-class="{hidden: collapsed}">
    <li ng-repeat="node in node.nodes" ui-tree-node ng-include="'nodes_renderer2.html'">
    </li>
  </ol>
</script>

<div class="container" ng-controller="adminRoleCtrl">
  <h2>Management roles</h2>
  <div class="row">
    <div class="col-sm-6">
      <h3>Tree Roles</h3>
      <div ui-tree id="tree1-root">
        <ol ui-tree-nodes="" ng-model="rolesList">
          <li ng-repeat="node in rolesList" ui-tree-node ng-include="'nodes_renderer2.html'"></li>
        </ol>
      </div>
        <br/>
        <button type="submit" ng-disabled="!editedFlag" class="btn btn-primary" ng-click="saveTree()">Save changes to DB</button>
    </div>

    <div class="col-sm-6">
      <h3>Import Roles from OneLogin?</h3>

    </div>
  </div>
</div>