CREATE  TABLE IF NOT EXISTS `users` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `team` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users and teams';

