<?php  $this->headScript()
            ->prependFile($this->basePath() . '/tocat-user/js/controllers/admin-group.js')
            ->prependFile($this->basePath() . '/vendor/angular-ui-grid/ui-grid.min.js')
            ->prependFile($this->basePath() . '/vendor/angular/angular.min.js');
       $this->headLink()
           ->prependStylesheet($this->basePath() . '/tocat-user/css/style.css')
           ->prependStylesheet($this->basePath() . '/vendor/angular-ui-grid/ui-grid.min.css'); ?>

<script type="text/javascript">
    var URL_SAVE_GROUP_LIST = '<?=$this->url('zfcadmin/groups', array('action' => 'save-bulk')) ?>';
    var URL_DELETE_GROUP = '<?=$this->url('zfcadmin/groups', array('action' => 'delete')) ?>';
    var URL_SAVE_GROUP = '<?=$this->url('zfcadmin/groups', array('action' => 'save')) ?>';
    var URL_SHOW_GROUP_LIST = '<?=$this->url('zfcadmin/groups', array('action' => 'list')) ?>';
</script>
<div>
    <div ng-controller="AdminGroupCtrl">
        <h2>Management Groups / Teams</h2>

        <div class="row">
            <div class="col-sm-8">
                <h3>Groups list</h3>
                <div ui-grid="gridOptions" ui-grid-selection ui-grid-edit ui-grid-resize-columns ui-grid-pinning
                     class="grid"></div>
            </div>
            <div class="col-sm-4">
                <h3>Group members</h3>
                <ul ng-model="groupsSelected">
                  <li ng-repeat="group in groupsSelected">
                      {{group.name}}
                      <ul>
                          <li ng-repeat="user in group.users">
                              {{user.display_name}} ({{user.email}})
                          </li>
                      </ul>
                  </li>
                </ul>
            </div>
        </div>
    </div>
</div>
