<span style="color: #f5f5f5;">
    <strong>
        <?php if ($this->displayName): ?>
            <span class="userpic"><?= $this->gravatar($this->zfcUserIdentity()->getEmail(), ['img_size' => 23]) ?></span>
            <a href="<?= $this->url('zfcuser/account') ?>"><?= $this->displayName ?></a> |
            <a href="<?= $this->url('zfcuser/logout') ?>">[<?= $this->translate('Sign Out'); ?>]</a>
        <?php else: ?>
            <?= $this->translate('Hello, guest') ?>
        <?php endif; ?>
    </strong>
</span>