<?php echo $this->partial('layout/partial/header.phtml', $this); ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by OpsWay Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->partial('layout/partial/footer.phtml', $this); ?>
