<style>
    .row table, .row table tr, .row table th, .row table td {
        border: dashed #777 1px;
        text-align: center;
    }
</style>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sTocat%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p>Enter to <a href="/apigility/welcome">Apigility Admin</a> </p>
</div>
<div class="row">
    <h3>Transactions</h3>
    <table>
        <thead>
        <tr><th>UID</th><th>Timestamp</th><th>Author UID</th> <th>Account UID</th> <th>Total</th><th>Comment</th></tr>
        </thead>
        <tbody>
        <?php foreach ($this->tx as $row): ?>
            <tr>
                <td><?= $row->uid ?></td>
                <td><?= $row->timestamp ?></td>
                <td><?= $row->author_uid ?></td>
                <td><?= $row->account_uid ?></td>
                <td><?= $row->total ?></td>
                <td><?= $row->comment ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
    <form method="post" id="payment_form" action="<?= $this->url('application/default', array('action' => 'order','controller' => 'index'))?>">
        <input type="hidden" name="uid">
    <table>
        <thead>
        <tr><th>UID</th><th>Name</th><th>Budget</th><th>Action</th></tr>
        </thead>
        <tbody>
        <?php foreach ($this->order as $row): ?>
            <tr>
                <td><?= $row->uid ?></td>
                <td><?= $row->name ?></td>
                <td><?= $row->budget ?></td>
                <td><input type="submit" name="action" value="Delete" onclick="if (confirm('Are you sure?')) { this.form.elements['uid'].value = '<?= $row->uid ?>'; } else { return false; }"></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td>&nbsp;</td>
            <td><input name="name" maxlength="100"/></td>
            <td><input name="budget" maxlength="10"/></td>
            <td><button type="submit">Add New</button></td>
        </tr>
        </tbody>
    </table>
    </form>

