<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' '. $this->translate('Tocat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/tocat-core/css/style.css')
                        ->prependStylesheet($this->basePath() . '/vendor/angular-ui-tree/dist/angular-ui-tree.min.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap.min.css') ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/tocat-core/js/navbar-menu.js')
            ->prependFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
            ->prependFile($this->basePath() . '/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/html5shiv/dist/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body class="ng-scope" ng-app="tocatApp">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home')?>"><img src="<?=$this->basePath('img/opsway-logo.png') ?>" alt="OpsWay" width="60%"/>&nbsp;<?=$this->translate('TOCAT')?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')
                                    ->menu()
                                    ->setUlClass('nav navbar-nav')
                                    ->setPartial('layout/partial/top-menu/navigation.phtml');
                    ?>
                    <p class="navbar-text navbar-right">
                        <?=$this->userTopWidget()?>
                    </p>
                </div><!--/.nav-collapse -->
            </div>
        </nav>