<style>
    .row table, .row table tr, .row table th, .row table td {
        border: dashed #777 1px;
        text-align: center;
    }
</style>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sTocat%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p>This application will provide easy money ecosystem for your company.</p>
    <p>Sorry, this is development build in demo mode. Follow us on <a href="https://github.com/opsway/tocat">GitHub</a></p>
</div>


<pre><?php print_r($this->test) ?></pre>