<style>
    .row table, .row table tr, .row table th, .row table td {
        border: dashed #777 1px;
        text-align: center;
    }
</style>
<div class="jumbotron">
    <h2><?= sprintf($this->translate('Welcome to %sOpsWay%s Dashboard'), '<span class="zf-green">', '</span>') ?></h2>
    <p>
        <?= $this->translate('This sandbox application where you can implement your idea. For example like "Calendar Booking Your Time" (look link in header)');?>
        <a href="https://github.com/opsway/tocat">GitHub</a>
    </p>
</div>
