<style>
    .row table, .row table tr, .row table th, .row table td {
        border: dashed #777 1px;
        text-align: center;
    }
</style>
<div class="jumbotron">
    <h2><?= sprintf($this->translate('Welcome to %sTOCAT%s Dashboard'), '<span class="zf-green">', '</span>') ?></h2>
    <p>
        <?= $this->translate('This application will provide easy money ecosystem for your company. Sorry, this is development build in demo mode. Follow us on');?>
        <a href="https://github.com/opsway/tocat">GitHub</a>
    </p>
</div>


<pre><?php print_r($this->test) ?></pre>